const colors={control:'#ffb86b',execution:'#63e6be',knowledge:'#79a8ff',connectivity:'#c792ff',governance:'#ff7d9c'};
const agents=[
 {id:'agent-a',name:'Agent Instance A',role:'规划与协调',x:330,y:72,tags:['Goal','Policy','Skills']},
 {id:'agent-b',name:'Agent Instance B',role:'研究与执行',x:500,y:72,tags:['Model','Tools','Memory']},
 {id:'agent-n',name:'Agent Instance N',role:'评审与协作',x:670,y:72,tags:['Context','IPC','Artifacts']}
];
const nodes=[
 {id:'security',name:'Security / Sandbox',code:'SECURITY',layer:'governance',layerName:'安全与治理',x:105,y:205,summary:'为 Agent、工具、模型与数据建立统一的身份、权限、隔离和策略边界。',duties:['身份与权限校验','执行环境隔离','密钥与敏感数据保护','策略执行与风险拦截'],input:['身份上下文','访问请求','安全策略'],output:['授权决策','隔离环境','风险事件']},
 {id:'communication',name:'Agent Communication Stack',code:'COMM STACK',layer:'connectivity',layerName:'连接与通信',x:500,y:188,summary:'负责 Agent、AgentOS 与外部客户端之间的标准化通信，不参与大模型选择与路由。',duties:['A2A 与 MCP 通信','Streaming / Webhook','协议发现与协商','跨 AgentOS 消息路由'],input:['Agent 消息','事件流','服务描述'],output:['标准通信消息','连接状态','远端 Agent 响应']},
 {id:'gateway',name:'Model Gateway',code:'MODEL GATEWAY',layer:'connectivity',layerName:'连接与通信',x:870,y:222,summary:'专门连接各类大模型服务，统一处理模型 API 适配、动态路由、成本、隐私与故障降级。',duties:['模型 API 统一适配','多模型动态路由','成本、延迟与配额优化','隐私过滤、熔断与降级'],input:['推理请求','模型路由策略','供应商状态'],output:['模型响应','Token 与成本记录','路由与降级结果']},
 {id:'scheduler',name:'Agent Scheduler',code:'SCHEDULER',layer:'control',layerName:'控制与编排',x:300,y:355,summary:'把目标转化为可执行任务，决定拆分粒度、依赖顺序、并发、重试与资源分配。',duties:['任务分解与依赖分析','并发与优先级调度','超时、重试和回退','模型与资源选择'],input:['目标','任务图','资源状态'],output:['Run 计划','调度事件','重试决策']},
 {id:'runtime',name:'Agent Runtime',code:'RUNTIME',layer:'execution',layerName:'执行与资源',x:500,y:355,summary:'运行 Agent Loop，维护单次执行上下文，并协调模型、工具、记忆与产物。',duties:['Agent Loop 执行','上下文装配','工具调用编排','中断与继续执行'],input:['Run 计划','上下文','模型与工具结果'],output:['动作','事件','中间与最终结果']},
 {id:'ipc',name:'Agent IPC',code:'IPC',layer:'connectivity',layerName:'连接与通信',x:700,y:355,summary:'支持同一 AgentOS 内多 Agent 之间的 handoff、事件、共享状态与 agents-as-tools。',duties:['Agent handoff','事件总线','共享状态协调','Agents as tools'],input:['Agent 消息','事件','共享引用'],output:['投递结果','订阅事件','协作上下文']},
 {id:'state',name:'State Manager',code:'STATE',layer:'knowledge',layerName:'状态与知识',x:150,y:548,summary:'管理 session、run、task 与 continuation 等运行态，是可恢复执行的事实来源。',duties:['Session / Run 状态','Task 状态机','Checkpoint','Continuation 与恢复'],input:['状态变更','事件','检查点'],output:['当前状态','恢复点','状态订阅']},
 {id:'memory',name:'Memory Manager',code:'MEMORY',layer:'knowledge',layerName:'状态与知识',x:340,y:548,summary:'管理长期记忆、用户偏好与项目知识，并决定何时写入、检索、更新和遗忘。',duties:['记忆分类与存储','检索与重排','更新、合并与遗忘','用户与项目知识隔离'],input:['对话与事件','知识片段','检索意图'],output:['相关记忆','记忆变更','引用证据']},
 {id:'workspace',name:'Workspace / Artifact',code:'WORKSPACE',layer:'execution',layerName:'执行与资源',x:530,y:548,summary:'为 Agent 提供可操作的文件、代码、数据与产物空间，并管理版本、所有权和生命周期。',duties:['文件与代码操作','Artifact 生命周期','版本与血缘','协作空间与锁'],input:['文件操作','代码变更','生成产物'],output:['文件引用','版本差异','可交付产物']},
 {id:'registry',name:'Tool / Skill Registry',code:'REGISTRY',layer:'execution',layerName:'执行与资源',x:720,y:548,summary:'发现、描述、授权和调用工具、MCP Server 与技能包，形成 AgentOS 的能力目录。',duties:['能力发现与检索','Schema 与版本管理','依赖和兼容性','安装、授权与调用'],input:['能力查询','工具描述','权限上下文'],output:['候选能力','调用端点','兼容性判断']},
 {id:'governance',name:'Observability / Governance',code:'GOVERNANCE',layer:'governance',layerName:'安全与治理',x:870,y:548,summary:'记录系统行为、成本、质量与责任链，为调试、评估、审计和治理提供依据。',duties:['Tracing / Logging / Metrics','成本与质量评估','审计与责任链','策略反馈与运营治理'],input:['全链路事件','指标','策略结果'],output:['Trace','评估报告','治理动作']}
];
const edges=[
 ['communication','scheduler','请求 / 任务'],['scheduler','runtime','Run 计划'],['runtime','ipc','handoff / event'],['ipc','communication','跨系统协作'],['runtime','gateway','模型请求'],['runtime','state','运行态'],['state','memory','记忆索引'],['runtime','memory','检索 / 写入'],['runtime','workspace','操作 / 产物'],['runtime','registry','能力查询 / 调用'],['registry','workspace','工具输出'],['security','communication','身份 / 策略'],['security','runtime','权限 / 隔离'],['runtime','governance','trace / metric'],['scheduler','governance','调度审计']
].map((e,i)=>({id:'e'+i,from:e[0],to:e[1],label:e[2]}));
const flows=[
 {id:'task',index:'01',name:'任务执行',description:'外部请求进入系统，经过编排、执行和模型调用形成结果。',nodes:['communication','scheduler','runtime','gateway'],edges:['e0','e1','e4']},
 {id:'memory',index:'02',name:'记忆循环',description:'Runtime 读写长期记忆，并通过 State 保持可恢复的运行上下文。',nodes:['runtime','state','memory'],edges:['e5','e6','e7']},
 {id:'tools',index:'03',name:'工具与产物',description:'发现并调用能力，将工具结果和最终交付物沉淀到工作空间。',nodes:['runtime','registry','workspace'],edges:['e9','e10','e8']},
 {id:'multi',index:'04',name:'多 Agent 协作',description:'通过 IPC 在本地协作，再经 Communication Stack 跨系统通信。',nodes:['scheduler','runtime','ipc','communication'],edges:['e1','e2','e3']}
];
let activeFlow='task',selected='runtime',playing=true,timer;
const byId=id=>nodes.find(n=>n.id===id);
function line(x1,y1,x2,y2,cls,label){const mx=(x1+x2)/2,my=(y1+y2)/2;return `<line class="${cls}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/><text class="edge-label" x="${mx}" y="${my-7}" text-anchor="middle">${label||''}</text>`}
function renderAgents(){document.querySelector('#agentLayer').innerHTML=agents.map(a=>`<article class="agent-card" style="left:${a.x/10}%;top:${a.y/6.5}%"><em>AGENT APPLICATION</em><strong>${a.name}</strong><small>${a.role}</small><div>${a.tags.map(t=>`<i>${t}</i>`).join('')}</div></article>`).join('')}
function renderMap(){const flow=flows.find(f=>f.id===activeFlow);const activeEdges=new Set(flow.edges),activeNodes=new Set(flow.nodes);let svg=agents.map(a=>line(a.x,a.y+28,500,325,`agent-edge ${['task','multi'].includes(flow.id)?'active':''}`,'')).join('');svg+=edges.map(e=>{const a=byId(e.from),b=byId(e.to);return line(a.x,a.y,b.x,b.y,`edge ${activeEdges.has(e.id)?'active':''}`,e.label)}).join('');document.querySelector('#edgeLayer').innerHTML=svg;document.querySelector('#nodeLayer').innerHTML=nodes.map(n=>`<button class="system-node ${selected===n.id?'selected':''} ${activeNodes.has(n.id)?'in-flow':''}" data-id="${n.id}" style="left:${n.x/10}%;top:${n.y/6.5}%;--node-color:${colors[n.layer]}"><em>${n.code}</em><strong>${n.name}</strong><small>${n.layerName}</small></button>`).join('');document.querySelectorAll('.system-node').forEach(el=>el.addEventListener('click',()=>{selected=el.dataset.id;renderMap();renderInspector()}));document.querySelector('#flowIndex').textContent=`FLOW / ${flow.index}`}
function renderFlows(){document.querySelector('#flowList').innerHTML=flows.map(f=>`<button class="flow-button ${f.id===activeFlow?'active':''}" data-flow="${f.id}"><span>${f.index}</span><div><strong>${f.name}</strong><small>${f.description}</small></div></button>`).join('');document.querySelectorAll('.flow-button').forEach(el=>el.addEventListener('click',()=>{activeFlow=el.dataset.flow;playing=false;syncPlay();renderAll()}));const f=flows.find(x=>x.id===activeFlow);document.querySelector('#flowSummary').innerHTML=`<small>当前场景</small><strong>${f.name}</strong><p>${f.description}</p>`}
function renderInspector(){const n=byId(selected);document.querySelector('#inspectorCode').textContent=n.code;document.querySelector('#inspectorContent').innerHTML=`<div class="inspector-head" style="--node-color:${colors[n.layer]}"><small>${n.layerName}</small><h3>${n.name}</h3></div><p class="summary">${n.summary}</p><section class="detail"><h4>核心职责</h4><ul>${n.duties.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="detail io"><div><b>INPUT</b>${n.input.map(x=>`<span>${x}</span>`).join('')}</div><div><b>OUTPUT</b>${n.output.map(x=>`<span>${x}</span>`).join('')}</div></section>`}
function syncPlay(){document.querySelector('#playButton').textContent=playing?'Ⅱ':'▶';document.querySelector('#playButton').setAttribute('aria-label',playing?'暂停自动播放':'开始自动播放');document.querySelector('#systemMap').classList.toggle('playing',playing);clearInterval(timer);if(playing)timer=setInterval(()=>{const i=flows.findIndex(f=>f.id===activeFlow);activeFlow=flows[(i+1)%flows.length].id;renderAll()},5600)}
function renderAll(){renderFlows();renderMap();renderInspector()}
document.querySelector('#playButton').addEventListener('click',()=>{playing=!playing;syncPlay()});document.querySelector('#labelsButton').addEventListener('click',e=>{const show=document.querySelector('#systemMap').classList.toggle('show-labels');e.target.textContent=show?'隐藏连线标签':'显示连线标签'});document.addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();playing=!playing;syncPlay()}});renderAgents();renderAll();syncPlay();
